// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AtomicsManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180901155438_ok")]
    partial class ok
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DAL.Models.Actions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("ProcessId");

                    b.Property<int>("TypeAction");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.ToTable("WorkActions");
                });

            modelBuilder.Entity("DAL.Models.ActionsHistories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActionsId");

                    b.Property<string>("Comment");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("DemandesId");

                    b.Property<int>("EtatId");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserId");

                    b.Property<DateTime>("dateOperation");

                    b.HasKey("Id");

                    b.HasIndex("ActionsId");

                    b.HasIndex("DemandesId");

                    b.HasIndex("EtatId");

                    b.HasIndex("UserId");

                    b.ToTable("AppActionsHistories");
                });

            modelBuilder.Entity("DAL.Models.ActionTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActionsId");

                    b.Property<int?>("GroupId");

                    b.Property<int>("Target");

                    b.HasKey("Id");

                    b.HasIndex("ActionsId");

                    b.HasIndex("GroupId");

                    b.ToTable("WorkActionTarget");
                });

            modelBuilder.Entity("DAL.Models.Activite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descriptions");

                    b.Property<string>("Name");

                    b.Property<int>("ProcessId");

                    b.Property<int>("TypeActivite");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.ToTable("WorkActivite");
                });

            modelBuilder.Entity("DAL.Models.ActiviteTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActiviteId");

                    b.Property<int?>("GroupId");

                    b.Property<int>("Target");

                    b.HasKey("Id");

                    b.HasIndex("ActiviteId");

                    b.HasIndex("GroupId");

                    b.ToTable("WorkActiviteTargets");
                });

            modelBuilder.Entity("DAL.Models.Agences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adresse");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("HeadName");

                    b.Property<bool>("IsMain");

                    b.Property<string>("Name");

                    b.Property<string>("Tel");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<int>("VillesId");

                    b.HasKey("Id");

                    b.HasIndex("VillesId");

                    b.ToTable("AppAgences");
                });

            modelBuilder.Entity("DAL.Models.APGmembers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApprobationLevelId");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("MemberId");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("ApprobationLevelId");

                    b.HasIndex("MemberId");

                    b.ToTable("AppAPGmembers");
                });

            modelBuilder.Entity("DAL.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("DAL.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Configuration");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("JobTitle");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("DAL.Models.ApprobationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal>("ExpensLimite");

                    b.Property<bool>("IsActvie");

                    b.Property<bool>("IsEnded");

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.Property<int>("NumberApprovalRequiered");

                    b.Property<bool>("Shared");

                    b.Property<int>("TypeApprovalGroup");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("AppApprobationLevel");
                });

            modelBuilder.Entity("DAL.Models.ApprobationWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ApprobationDate");

                    b.Property<string>("Comment");

                    b.Property<int>("DemandesId");

                    b.Property<int>("GlobalStatut");

                    b.Property<int?>("LevelId");

                    b.Property<int>("LevelStatut");

                    b.Property<string>("UserId");

                    b.Property<int>("ValitationRequieredNumber");

                    b.HasKey("Id");

                    b.HasIndex("DemandesId");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("AppApprobationWorkflow");
                });

            modelBuilder.Entity("DAL.Models.BankInfos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountName");

                    b.Property<string>("AccountNumber");

                    b.Property<string>("Adrresse");

                    b.Property<string>("BankName");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email");

                    b.Property<int>("FournisseursId");

                    b.Property<string>("IBAN");

                    b.Property<string>("TelephoneNumbers");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<int?>("VillesId");

                    b.HasKey("Id");

                    b.HasIndex("BankName");

                    b.HasIndex("FournisseursId")
                        .IsUnique();

                    b.HasIndex("VillesId");

                    b.ToTable("AppBankInfos");
                });

            modelBuilder.Entity("DAL.Models.ComptesInternes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Label");

                    b.Property<string>("NumCompte");

                    b.Property<int?>("TypeComptesId");

                    b.HasKey("Id");

                    b.HasIndex("TypeComptesId");

                    b.ToTable("AppComptesInternes");
                });

            modelBuilder.Entity("DAL.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateModified");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<int>("Gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("AppCustomers");
                });

            modelBuilder.Entity("DAL.Models.Demandes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CurrentStatId");

                    b.Property<DateTime>("DateDemande");

                    b.Property<DateTime>("DateLivraison");

                    b.Property<DateTime>("DateLivraisonPrevu");

                    b.Property<int?>("FournisseursId");

                    b.Property<decimal>("Montant");

                    b.Property<string>("Motif");

                    b.Property<int>("Nature");

                    b.Property<int>("ProcessId");

                    b.Property<int>("ProductId");

                    b.Property<int>("Quantite");

                    b.Property<int>("TypeLigne");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("userId");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStatId");

                    b.HasIndex("FournisseursId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("ProductId");

                    b.HasIndex("userId");

                    b.ToTable("AppDemandes");
                });

            modelBuilder.Entity("DAL.Models.DemandesAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActionsId");

                    b.Property<int>("DemandesId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsComplete");

                    b.Property<int>("TransitionId");

                    b.HasKey("Id");

                    b.HasIndex("ActionsId");

                    b.HasIndex("DemandesId");

                    b.HasIndex("TransitionId");

                    b.ToTable("WorkDemandesAction");
                });

            modelBuilder.Entity("DAL.Models.Departements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("AppDepartements");
                });

            modelBuilder.Entity("DAL.Models.Devises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeIso");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Label");

                    b.Property<string>("Symbole");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("Label");

                    b.ToTable("AppDevises");
                });

            modelBuilder.Entity("DAL.Models.DocumentsFournisseurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DocumentName");

                    b.Property<byte[]>("Documents");

                    b.Property<int?>("FournisseursId");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<int>("typeDocFournisseurs");

                    b.HasKey("Id");

                    b.HasIndex("FournisseursId");

                    b.ToTable("AppDocumentsFournisseurs");
                });

            modelBuilder.Entity("DAL.Models.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adresse");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("FormeJuridique");

                    b.Property<byte[]>("Logo");

                    b.Property<string>("Name");

                    b.Property<string>("Tel");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("email");

                    b.Property<string>("titre");

                    b.Property<string>("webSite");

                    b.HasKey("Id");

                    b.ToTable("AppEntreprise");
                });

            modelBuilder.Entity("DAL.Models.EntrepriseUserInfos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AgencesId");

                    b.Property<string>("ApplicationUserId");

                    b.Property<int>("DepartementsId");

                    b.Property<int>("ServicesId");

                    b.HasKey("Id");

                    b.HasIndex("AgencesId");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("DepartementsId");

                    b.HasIndex("ServicesId");

                    b.ToTable("AppEntrepriseUserInfos");
                });

            modelBuilder.Entity("DAL.Models.Etat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("ProcessId");

                    b.Property<int>("TypeEtats");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.ToTable("WorkEtats");
                });

            modelBuilder.Entity("DAL.Models.EtatActivite", b =>
                {
                    b.Property<int>("ActiviteId");

                    b.Property<int>("EtatId");

                    b.HasKey("ActiviteId", "EtatId");

                    b.HasIndex("EtatId");

                    b.ToTable("WorkEtatActivite");
                });

            modelBuilder.Entity("DAL.Models.FichierDemandes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateEnvoi");

                    b.Property<int>("DemandesId");

                    b.Property<byte[]>("Fichier");

                    b.Property<string>("NomFichier");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("DemandesId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkFichierDemandes");
                });

            modelBuilder.Entity("DAL.Models.Fournisseurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adresse");

                    b.Property<string>("AlternatePhoneNumber");

                    b.Property<string>("CodePostale");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("DevisesId");

                    b.Property<string>("Email");

                    b.Property<string>("Emailcommande");

                    b.Property<string>("FormeJuridique");

                    b.Property<string>("NomDg");

                    b.Property<string>("NomSociete");

                    b.Property<string>("NumTVAintracommunautare");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("TelCommande");

                    b.Property<string>("TelDg");

                    b.Property<string>("Titre");

                    b.Property<int>("TypePayments");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<int?>("VillesId");

                    b.HasKey("Id");

                    b.HasIndex("DevisesId");

                    b.HasIndex("Titre");

                    b.HasIndex("VillesId");

                    b.ToTable("AppFournisseurs");
                });

            modelBuilder.Entity("DAL.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("ProcessId");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.ToTable("WorkGroup");
                });

            modelBuilder.Entity("DAL.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GroupId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkGroupeMember");
                });

            modelBuilder.Entity("DAL.Models.InfosDemandes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DemandesId");

                    b.Property<string>("Note");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("DemandesId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkInfosDemandes");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CashierId");

                    b.Property<string>("Comments")
                        .HasMaxLength(500);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CustomerId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateModified");

                    b.Property<decimal>("Discount");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.HasIndex("CustomerId");

                    b.ToTable("AppOrders");
                });

            modelBuilder.Entity("DAL.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal>("Discount");

                    b.Property<int>("OrderId");

                    b.Property<int>("ProductId");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("AppOrderDetails");
                });

            modelBuilder.Entity("DAL.Models.Pays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodePays");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Name");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("AppPays");
                });

            modelBuilder.Entity("DAL.Models.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("WorkProcess");
                });

            modelBuilder.Entity("DAL.Models.ProcessAdmin", b =>
                {
                    b.Property<int>("ProcessId");

                    b.Property<string>("UserId");

                    b.HasKey("ProcessId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkProcessAdmins");
                });

            modelBuilder.Entity("DAL.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("BuyingPrice");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateModified");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<int>("FournisseursId");

                    b.Property<byte[]>("Icon")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDiscontinued");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("ProductCategoryId");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("FournisseursId");

                    b.HasIndex("Name");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("AppProducts");
                });

            modelBuilder.Entity("DAL.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateModified");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("Icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("AppProductCategories");
                });

            modelBuilder.Entity("DAL.Models.Secteurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Name");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("description");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("AppSecteurs");
                });

            modelBuilder.Entity("DAL.Models.SecteursFournisseurs", b =>
                {
                    b.Property<int>("FournisseursId");

                    b.Property<int>("SecteursId");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("FournisseursId", "SecteursId");

                    b.HasIndex("SecteursId");

                    b.ToTable("AppSecteursFournisseurs");
                });

            modelBuilder.Entity("DAL.Models.Services", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DepartementsId");

                    b.Property<string>("Description");

                    b.Property<string>("HeadId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DepartementsId");

                    b.HasIndex("HeadId");

                    b.ToTable("AppServices");
                });

            modelBuilder.Entity("DAL.Models.Stakeholders", b =>
                {
                    b.Property<int>("DemandesId");

                    b.Property<string>("UserId");

                    b.HasKey("DemandesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkStakeholders");
                });

            modelBuilder.Entity("DAL.Models.Transition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("EtatActuelId");

                    b.Property<int>("EtatSuivantId");

                    b.Property<int>("ProcessId");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("EtatActuelId");

                    b.HasIndex("EtatSuivantId");

                    b.HasIndex("ProcessId");

                    b.ToTable("WorkTransition");
                });

            modelBuilder.Entity("DAL.Models.TransitionActions", b =>
                {
                    b.Property<int>("ActionsId");

                    b.Property<int>("TransitionId");

                    b.HasKey("ActionsId", "TransitionId");

                    b.HasIndex("TransitionId");

                    b.ToTable("WorkTransitionActions");
                });

            modelBuilder.Entity("DAL.Models.TransitionActivite", b =>
                {
                    b.Property<int>("ActiviteId");

                    b.Property<int>("TransitionId");

                    b.HasKey("ActiviteId", "TransitionId");

                    b.HasIndex("TransitionId");

                    b.ToTable("WorkTransitionActivite");
                });

            modelBuilder.Entity("DAL.Models.TypeComptes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("NatureCompte");

                    b.HasKey("Id");

                    b.ToTable("AppTypeComptes");
                });

            modelBuilder.Entity("DAL.Models.Villes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Name");

                    b.Property<int>("PaysId");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("PaysId");

                    b.ToTable("AppVilles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("OpenIddict.Models.OpenIddictApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientId")
                        .IsRequired();

                    b.Property<string>("ClientSecret");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken();

                    b.Property<string>("ConsentType");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Permissions");

                    b.Property<string>("PostLogoutRedirectUris");

                    b.Property<string>("Properties");

                    b.Property<string>("RedirectUris");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications");
                });

            modelBuilder.Entity("OpenIddict.Models.OpenIddictAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationId");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken();

                    b.Property<string>("Properties");

                    b.Property<string>("Scopes");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("Subject")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("OpenIddictAuthorizations");
                });

            modelBuilder.Entity("OpenIddict.Models.OpenIddictScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken();

                    b.Property<string>("Description");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Properties");

                    b.Property<string>("Resources");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes");
                });

            modelBuilder.Entity("OpenIddict.Models.OpenIddictToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationId");

                    b.Property<string>("AuthorizationId");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken();

                    b.Property<DateTimeOffset?>("CreationDate");

                    b.Property<DateTimeOffset?>("ExpirationDate");

                    b.Property<string>("Payload");

                    b.Property<string>("Properties");

                    b.Property<string>("ReferenceId");

                    b.Property<string>("Status");

                    b.Property<string>("Subject")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.ToTable("OpenIddictTokens");
                });

            modelBuilder.Entity("DAL.Models.Actions", b =>
                {
                    b.HasOne("DAL.Models.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.ActionsHistories", b =>
                {
                    b.HasOne("DAL.Models.Actions", "Actions")
                        .WithMany("ActionsHistories")
                        .HasForeignKey("ActionsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Demandes", "Demandes")
                        .WithMany("ActionsHistories")
                        .HasForeignKey("DemandesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Etat", "Etat")
                        .WithMany("ActionsHistories")
                        .HasForeignKey("EtatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.ApplicationUser", "User")
                        .WithMany("ActionsHistories")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DAL.Models.ActionTarget", b =>
                {
                    b.HasOne("DAL.Models.Actions", "Actions")
                        .WithMany("ActionTarget")
                        .HasForeignKey("ActionsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Group", "Group")
                        .WithMany("ActionTarget")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("DAL.Models.Activite", b =>
                {
                    b.HasOne("DAL.Models.Process", "Process")
                        .WithMany("Activite")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.ActiviteTarget", b =>
                {
                    b.HasOne("DAL.Models.Activite", "Activite")
                        .WithMany("ActiviteTarget")
                        .HasForeignKey("ActiviteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Group", "Group")
                        .WithMany("ActiviteTarget")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("DAL.Models.Agences", b =>
                {
                    b.HasOne("DAL.Models.Villes", "Villes")
                        .WithMany()
                        .HasForeignKey("VillesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.APGmembers", b =>
                {
                    b.HasOne("DAL.Models.ApprobationLevel", "ApprobationLevel")
                        .WithMany("APGmembers")
                        .HasForeignKey("ApprobationLevelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.ApplicationUser", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");
                });

            modelBuilder.Entity("DAL.Models.ApprobationWorkflow", b =>
                {
                    b.HasOne("DAL.Models.Demandes", "Demandes")
                        .WithMany()
                        .HasForeignKey("DemandesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.ApprobationLevel", "Level")
                        .WithMany("ApprobationWorkflow")
                        .HasForeignKey("LevelId");

                    b.HasOne("DAL.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DAL.Models.BankInfos", b =>
                {
                    b.HasOne("DAL.Models.Fournisseurs", "Fournisseurs")
                        .WithOne("BankInfos")
                        .HasForeignKey("DAL.Models.BankInfos", "FournisseursId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Villes", "Villes")
                        .WithMany("BankInfos")
                        .HasForeignKey("VillesId");
                });

            modelBuilder.Entity("DAL.Models.ComptesInternes", b =>
                {
                    b.HasOne("DAL.Models.TypeComptes", "TypeComptes")
                        .WithMany("ComptesInternes")
                        .HasForeignKey("TypeComptesId");
                });

            modelBuilder.Entity("DAL.Models.Demandes", b =>
                {
                    b.HasOne("DAL.Models.Etat", "CurrentStat")
                        .WithMany("Demandes")
                        .HasForeignKey("CurrentStatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Fournisseurs")
                        .WithMany("Demandes")
                        .HasForeignKey("FournisseursId");

                    b.HasOne("DAL.Models.Process", "Process")
                        .WithMany("Demandes")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Product", "Product")
                        .WithMany("Demandes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.ApplicationUser", "user")
                        .WithMany("Demandes")
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("DAL.Models.DemandesAction", b =>
                {
                    b.HasOne("DAL.Models.Actions", "Actions")
                        .WithMany("DemandesAction")
                        .HasForeignKey("ActionsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Demandes", "Demandes")
                        .WithMany("DemandesAction")
                        .HasForeignKey("DemandesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Transition", "Transition")
                        .WithMany("DemandesAction")
                        .HasForeignKey("TransitionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.DocumentsFournisseurs", b =>
                {
                    b.HasOne("DAL.Models.Fournisseurs", "Fournisseurs")
                        .WithMany("DocumentsFournisseurs")
                        .HasForeignKey("FournisseursId");
                });

            modelBuilder.Entity("DAL.Models.EntrepriseUserInfos", b =>
                {
                    b.HasOne("DAL.Models.Agences", "Agences")
                        .WithMany("EntrepriseUserInfos")
                        .HasForeignKey("AgencesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("EntrepriseUserInfos")
                        .HasForeignKey("DAL.Models.EntrepriseUserInfos", "ApplicationUserId");

                    b.HasOne("DAL.Models.Departements", "Departements")
                        .WithMany("Head")
                        .HasForeignKey("DepartementsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Services", "Services")
                        .WithMany("EntrepriseUserInfos")
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.Etat", b =>
                {
                    b.HasOne("DAL.Models.Process", "Process")
                        .WithMany("Etat")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.EtatActivite", b =>
                {
                    b.HasOne("DAL.Models.Activite", "Activite")
                        .WithMany("EtatActivite")
                        .HasForeignKey("ActiviteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Etat", "Etat")
                        .WithMany("EtatActivite")
                        .HasForeignKey("EtatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.FichierDemandes", b =>
                {
                    b.HasOne("DAL.Models.Demandes", "Demandes")
                        .WithMany("FichierDemandes")
                        .HasForeignKey("DemandesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DAL.Models.Fournisseurs", b =>
                {
                    b.HasOne("DAL.Models.Devises", "Devises")
                        .WithMany("Fournisseurs")
                        .HasForeignKey("DevisesId");

                    b.HasOne("DAL.Models.Villes", "Villes")
                        .WithMany("Fournisseurs")
                        .HasForeignKey("VillesId");
                });

            modelBuilder.Entity("DAL.Models.Group", b =>
                {
                    b.HasOne("DAL.Models.Process", "Process")
                        .WithMany("Group")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.GroupMember", b =>
                {
                    b.HasOne("DAL.Models.Group", "Group")
                        .WithMany("GroupeMember")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.ApplicationUser", "User")
                        .WithMany("GroupeMember")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DAL.Models.InfosDemandes", b =>
                {
                    b.HasOne("DAL.Models.Demandes", "Demandes")
                        .WithMany("InfosDemandes")
                        .HasForeignKey("DemandesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.HasOne("DAL.Models.ApplicationUser", "Cashier")
                        .WithMany()
                        .HasForeignKey("CashierId");

                    b.HasOne("DAL.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.OrderDetail", b =>
                {
                    b.HasOne("DAL.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.ProcessAdmin", b =>
                {
                    b.HasOne("DAL.Models.Process", "Process")
                        .WithMany("ProcessAdmin")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.ApplicationUser", "User")
                        .WithMany("ProcessAdmin")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.Product", b =>
                {
                    b.HasOne("DAL.Models.Fournisseurs", "Fournisseurs")
                        .WithMany("Product")
                        .HasForeignKey("FournisseursId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.SecteursFournisseurs", b =>
                {
                    b.HasOne("DAL.Models.Fournisseurs", "Fournisseurs")
                        .WithMany("SecteursFournisseurs")
                        .HasForeignKey("FournisseursId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Secteurs", "Secteurs")
                        .WithMany("SecteursFournisseurs")
                        .HasForeignKey("SecteursId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.Services", b =>
                {
                    b.HasOne("DAL.Models.Departements", "Departements")
                        .WithMany("Services")
                        .HasForeignKey("DepartementsId");

                    b.HasOne("DAL.Models.ApplicationUser", "Head")
                        .WithMany()
                        .HasForeignKey("HeadId");
                });

            modelBuilder.Entity("DAL.Models.Stakeholders", b =>
                {
                    b.HasOne("DAL.Models.Demandes", "Demandes")
                        .WithMany("Stakeholders")
                        .HasForeignKey("DemandesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.ApplicationUser", "User")
                        .WithMany("Stakeholders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.Transition", b =>
                {
                    b.HasOne("DAL.Models.Etat", "EtatActuel")
                        .WithMany()
                        .HasForeignKey("EtatActuelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Etat", "EtatSuivant")
                        .WithMany()
                        .HasForeignKey("EtatSuivantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Process", "Process")
                        .WithMany("Transition")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.TransitionActions", b =>
                {
                    b.HasOne("DAL.Models.Actions", "Actions")
                        .WithMany("TransitionActions")
                        .HasForeignKey("ActionsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Transition", "Transition")
                        .WithMany("TransitionActions")
                        .HasForeignKey("TransitionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.TransitionActivite", b =>
                {
                    b.HasOne("DAL.Models.Activite", "Activite")
                        .WithMany("TransitionActivite")
                        .HasForeignKey("ActiviteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Transition", "Transition")
                        .WithMany("TransitionActivite")
                        .HasForeignKey("TransitionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Models.Villes", b =>
                {
                    b.HasOne("DAL.Models.Pays", "Pays")
                        .WithMany("Villes")
                        .HasForeignKey("PaysId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DAL.Models.ApplicationRole")
                        .WithMany("Claims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DAL.Models.ApplicationUser")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DAL.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DAL.Models.ApplicationRole")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.ApplicationUser")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DAL.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OpenIddict.Models.OpenIddictAuthorization", b =>
                {
                    b.HasOne("OpenIddict.Models.OpenIddictApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");
                });

            modelBuilder.Entity("OpenIddict.Models.OpenIddictToken", b =>
                {
                    b.HasOne("OpenIddict.Models.OpenIddictApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.Models.OpenIddictAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");
                });
#pragma warning restore 612, 618
        }
    }
}
